#                  _   _                   ___ _         _                     Our plugins: https://alonsoaliaga.com/plugins
#                 /_\ | |___ _ _  ___ ___ / __| |_  __ _| |_                   Support server: https://alonsoaliaga.com/discord
#                / _ \| / _ \ ' \(_-</ _ \ (__| ' \/ _` |  _|                  Youtube: https://alonsoaliaga.com/play
#               /_/ \_\_\___/_||_/__/\___/\___|_||_\__,_|\__|                  Test server: plugins.alonsoaliaga.com
#                          by AlonsoAliaga                                     Twitch: https://alonsoaliaga.com/twitch
#           Considering donating? https://alonsoaliaga.com/donate              Thanks for using my plugin <3
# ======================================================================================================================================
# |              Downloaded this jar in a server setup? Tell the author he is NOT allowed to upload someone else work!                 |
# |   Update to latest version as soon as possible. Support WON'T be given when using old versions. Specially from downloaded setups.  |
# | Remember: Support is only provided for .jar files downloaded DIRECTLY from spigotmc.org! Other files will be considered as invalid |
# |        as they are NOT the same .jar file the developer (me) uploaded and I cannot guarantee that the file is safe or not.         |
# |                   If you have issues with setup configs. Tell the setup author to update his config file.                          |
# |                          Download original plugin directly from https://alonsoaliaga.com/AlonsoChat                                |
# ======================================================================================================================================
Messages:
  No-permission: "&cYou don't have permission to do this."
  Reloaded: "&aSome messages and options have been reloaded. Other may require a restart!"
  Invalid-player: "&cPlayer is not online!"
  Chat:
    Bypass: "&cTarget player bypasses this command!"
    Bypass-notify: "&c☠ &6&lSomeone ({PLAYER}) attempted to make you chat a message&f: {MESSAGE}"
    Success: "&a&lPlayer {PLAYER} will send your message!"
    No-command: "&cFor security reasons you cannot execute commands for players!"
    No-command-notify: "&c☠ &6&lSomeone ({PLAYER}) attempted to make you use a command&f: {COMMAND}"
  Clear-chat:
    Cleared-by: "&6Chat has been cleared by %vault_prefix%%player_name%"
    Cleared-by-bypass: "&6Chat has been cleared by %vault_prefix%%player_name%&6! &aYou are immune!"
    Cleared-by-console: "&6Chat has been cleared by &eConsole&6!"
    Cleared-by-console-bypass: "&6Chat has been cleared by &eConsole&6! &aYou are immune!"
  Hex:
    Invalid-color: "&cAt least one of the color is not a valid color!"
    Click: "&7(Click to copy/suggest)"
  Help:
    Admin:
    - "&5 /alonsochat gradient [HEX1] [HEX2] [Text] &f- &dTest 2 color gradient"
    - "&5 /alonsochat clearchat [-s] &f- &dClears chat for online players"
    - "&5 /alonsochat chat <player> <message> &f- &dChat as target player"
    - "&5 /alonsochat reload &f- &dReload configuration (Restart recommended)"
    Staff:
    - "&5 /alonsochat gradient [HEX1] [HEX2] [Text] &f- &dTest 2 color gradient"
    - "&5 /alonsochat clearchat [-s] &f- &dClears chat for online players"
    - "&5 /alonsochat reload &f- &dReload configuration (Restart recommended)"
    User: []
  Links:
    #Placeholders from PlaceholderAPI can be used here.
    #Additional placeholders:
    # {LINK} - Replaced with the link that matches Options.Formatting.Regex.URL-link regex.
    # {FULL_LINK} - Replaced with the link that matches Options.Formatting.Regex.URL-color regex.
    Hover:
    - "&eClick to open link!"

Permissions:
  #For admin help message.
  Admin: "alonsochat.admin"
  #For staff help message.
  Staff: "alonsochat.staff"
  Clear-chat: "alonsochat.staff.clearchat"
  Clear-chat-bypass: "alonsochat.staff.clearchat.bypass"
  Sudo-chat: "alonsochat.staff.sudochat"
  Sudo-chat-bypass: "alonsochat.staff.sudochat.bypass"
  Sudo-chat-bypass-notify: "alonsochat.staff.sudochat.bypass.notify"
  #Permission to use /alonsochat hex sub command to test hex gradients.
  Hex: "alonsochat.hex"
  #Set the permissions below to "none" to not require permissions.
  Styling:
    Color: "alonsochat.styling.color"
    Hex-color: "alonsochat.styling.hex"
    Bold: "alonsochat.styling.bold"
    Strikethrough: "alonsochat.styling.strikethrough"
    Obfuscated: "alonsochat.styling.obfuscated"
    Underline: "alonsochat.styling.underline"
    Italic: "alonsochat.styling.italic"
    Reset: "alonsochat.styling.reset"
    URL: "alonsochat.styling.url"

Options:
  #Enable only if the developer asks you to do it otherwise you'll get a big spam in console and server chat.
  Debug: false
  #Option added to hide some information on load like "Loading X feature.." if there are too many of them.
  #Might not apply in all cases as some log ARE NECESSARY for me to understand issues if you have any. Don't insist.
  Log-mode: true
  Chat:
    #If disabled plugin will not format chat. This plugin is for chat formatting so disabling this makes no sense. Keep it enabled!
    Enabled: true
    #If enabled, chat event will be cancelled. If disabled, only recipients list will be cleared. Recommended to leave this enabled!
    Cancel-event: true
    #This option is HIGHLY UNSTABLE. This will create a new message for each listener as this uses relational placeholders
    #for plugins like Factions where you can read relation between player and audience. I highly recommend you to LEAVE THIS DISABLED.
    #But it's up to you, if enabled, you accept I cannot help you with issues related as I HAVE NEVER USED a faction plugin.
    Relational: false
    #If enabled, chat message will appear in console log as normal minecraft.
    Console-chat:
      Enabled: true
      Format: "[CHAT]{PLAYER}: {MESSAGE}"
  #You want to support the developer leaving the first line in help menu that contains plugin name and version? <3
  Support-developer: true
  Command:
    #Custom main command. REQUIRES RESTART TO APPLY CHANGES.
    Main: "alonsochat"
    #Custom aliases. REQUIRES RESTART TO APPLY CHANGES.
    Aliases:
    - "achat"
  Formatting:
    Regex:
      #Regex top detect URLs and URL with color codes before. PLEASE DO NO MODIFY if you don't know what you are doing.
      #YOU WON'T GET ANY SUPPORT FOR THIS PART. THIS IS ONLY AVAILABLE IN THE PART WHERE {MESSAGE} is included.
      #URL-color: '((&#[a-f0-9]{6})?(&[a-f0-9klmnor])*)?(https|http):\/\/([-\w_.]+\.[a-z][\w]{1,7})(\/\S*)?'
      URL-color: '((&#[a-f0-9]{6})?(&[a-f0-9klmnor])*)?(https|http):\/\/([-\w_.]+\.[a-z][\w]{1,7})(\/\S*)?'
      #URL-only: '(https|http):\/\/([-\w_.]+\.[a-z][\w]{1,7})(\/\S*)?'
      URL-link: '(https|http):\/\/([-\w_.]+\.[a-z][\w]{1,7})(\/\S*)?'
  Colors:
    #This is an attempt to make hex color look as close as possible to minecraft native colors for 1.8 - 1.15 players.
    Fix: true
  Placeholders:
    #This is ONLY USED FOR %alonsochat_restorehex_ANOTHERPLACECHOLDER%
    #Do NOT modify if you don't know what it does.
    Hex-format: "&#{COLOR}"
  #If empty Worlds: [] messages sent in all worlds will be formatted.
  #If worlds specified only messages sent in those worlds will be formatted.
  #Useful for minigame servers where you only want to format messages in "lobby" worlds.
  #To add worlds simply do it like this
  # Worlds:
  # - world
  # - lobby
  Worlds: []
  Clear-chat:
    #Some clients decide chat spam by combining similar messages into one by adding [x2], [x10], etc.
    #When enabled, this make all empty messages different by combining all types of format codes randomly. (&c&r&a&l)
    #Allowed modes:
    # NORMAL - Normal behavior (repeasts, " " in chat. Recommended)
    # UNIQUE - Makes each line unique (not recommended)
    # LINE_BREAK - Sends one single message with many line breaks (not recommended)
    Mode: NORMAL
    #Amount of empty lines that will be sent to players
    Lines: 150

Updates:
  #Auto update configuration? Enabling will delete comments.
  Auto-update-configuration: true
  #Check for updates? Recommended to keep it enabled.
  Check-updates: true
  #Notify updates when player with permission joins the server?
  Notify-updates: true
  #Permission required to receive update message.
  Permission: "alonsochat.update"
  #Message to send when update is found.
  Message: "&5[AlonsoChat] &eA new update has been found! You are using version {CURRENT}. Download version {NEW} here &c{LINK}"
